version: "3.2"
services:
  springboot:
    build:
      context: '.'
    networks:
      - springnet
    ports:
      - "8080:8080"
    container_name: viki-springboot
  nginx:
    image: nginx
    depends_on:
      - springboot
    networks:
      - springnet
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    container_name: viki-nginx
networks:
  springnet:

